=== hmrc/individual-losses-api/resources/public/api/conf/2.0/schemas/lossClaims/retrieveClaim/retrieve_response.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Loss Claim",
    "description": "Loss Claim",
    "type": "object",
    "properties": {
        "typeOfLoss" : {
            "type" : "string",
            "description": "The type of business the loss applies to.",
            "enum": ["self-employment", "uk-property-non-fhl"]
        },
        "selfEmploymentId" : {
            "type": "string",
            "description": "An identifier for the self-employment business, unique to the customer.",
            "example": "XGIS00000001319",
            "pattern": "^X[A-Z0-9]{1}IS[0-9]{11}$"
        },
        "typeOfClaim": {
            "type": "string",
            "description": "The type of claim to be applied.",
            "enum": ["carry-forward", "carry-sideways", "carry-sideways-fhl", "carry-forward-to-carry-sideways"]
        },
        "taxYear": {
            "type": "string",
            "description": "The tax year the data applies to, for example, 2019-20. The start year and end year must not span two tax years. No gaps are allowed, for example, 2019-21 is not valid. The minimum tax year is 2019-20.",
            "example": "2019-20"
        },
        "lastModified": {
            "type": "string",
            "description": "The timestamp when the entry was created or last modified",
            "example": "2020-07-11T12:13:48.763Z",
            "pattern": "^2[0-9]{3}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{0,3}|)Z$"
        },
        "links": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "A list of endpoint links that indicate possible actions related to the current resource",
                "properties": {
                    "href": {
                        "description": "The relative url of the endpoint",
                        "type": "string",
                        "example": "/individuals/losses/{nino}/loss-claims/{claimId}"
                    },
                    "rel": {
                        "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource",
                        "type": "string",
                        "enum": [
                            "self",
                            "amend-loss-claim",
                            "delete-loss-claim"
                        ]
                    },
                    "method": {
                        "description": "The HTTP method type for the endpoint",
                        "type": "string",
                        "enum": [
                            "GET",
                            "POST",
                            "DELETE"
                        ]
                    }
                },
                "required": [
                    "href",
                    "rel",
                    "method"
                ]
            }
        }
    },
    "required": ["typeOfLoss", "typeOfClaim", "taxYear"]
}

=== hmrc/individual-losses-api/resources/public/api/conf/3.0/examples/lossClaims/retrieveClaim/retrieve_non_fhl_response.json
{
    "typeOfLoss":"uk-property-non-fhl",
    "typeOfClaim": "carry-sideways",
    "taxYear": "2019-20",
    "lastModified" : "2020-07-11T12:15:34.734Z",
    "links": [
        {
            "href": "/individuals/losses/TC663795B/loss-claims/1234568790ABCDE",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "/individuals/losses/TC663795B/loss-claims/1234568790ABCDE",
            "rel": "delete-loss-claim",
            "method": "DELETE"
        },
        {
            "href": "/individuals/losses/TC663795B/loss-claims/1234568790ABCDE/change-type-of-claim",
            "rel": "amend-loss-claim",
            "method": "POST"
        }
    ]
}
