=== hmrc/individual-losses-api/resources/public/api/conf/2.0/schemas/broughtForwardLosses/retrieveBFLoss/retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Brought Forward Loss",
  "description": "Brought Forward Loss",
  "type": "object",
  "properties": {
    "typeOfLoss": {
      "type": "string",
      "enum": [
        "self-employment",
        "self-employment-class4",
        "uk-property-fhl",
        "uk-property-non-fhl"
      ],
      "description": "The type of business the loss applies to."
    },
    "selfEmploymentId": {
      "type": "string",
      "description": "An identifier for the self-employment business, unique to the customer.",
      "example": "XGIS00000001319",
      "pattern": "^X[A-Z0-9]{1}IS[0-9]{11}$"
    },
    "lossAmount": {
      "type": "number",
      "description": "Brought Forward Loss amount related to UK property or self-employment business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
      "example": "12345.67"
    },
    "taxYear": {
      "type": "string",
      "description": "The tax year the data applies to, for example, 2018-19. The start year and end year must not span two tax years. No gaps are allowed, for example, 2018-20 is not valid. The minimum tax year is 2018-19.",
      "example": "2018-19"
    },
    "lastModified": {
      "type": "string",
      "description": "The timestamp when the entry was created or last modified.",
      "format": "date-time",
      "pattern": "^2[0-9]{3}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{0,3}|)Z$",
      "example": "2018-07-13T12:13:48.763Z"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint",
            "type": "string",
            "example": "/individuals/losses/{nino}/brought-forward-losses/{lossId}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource",
            "type": "string",
            "enum": [
              "self",
              "amend-brought-forward-loss",
              "delete-brought-forward-loss"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint",
            "type": "string",
            "enum": [
              "GET",
              "POST",
              "DELETE"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ]
      }
    }
  },
  "required": [
    "typeOfLoss",
    "lossAmount",
    "taxYear",
    "lastModified"
  ]
}

=== hmrc/individual-losses-api/resources/public/api/conf/2.0/examples/broughtForwardLosses/amendBFLoss/amend_seClass4_response.json
{
  "typeOfLoss": "self-employment-class4",
  "selfEmploymentId": "XGIS00000001319",
  "lossAmount": 12345.67,
  "taxYear": "2018-19",
  "lastModified": "2018-07-13T12:13:48.763Z",
  "links": [
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/1234568790ABCDE",
      "rel": "self",
      "method": "GET"
    }
  ]
}

=== hmrc/individual-losses-api/resources/public/api/conf/3.0/examples/broughtForwardLosses/retrieveBFLoss/retrieve_fhl_response.json
{
  "typeOfLoss": "uk-property-fhl",
  "lossAmount": 12345.67,
  "taxYear": "2018-19",
  "lastModified": "2018-07-13T12:13:48.763Z",
  "links": [
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/1234568790ABCDE",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/1234568790ABCDE",
      "rel": "delete-brought-forward-loss",
      "method": "DELETE"
    },
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/1234568790ABCDE/change-loss-amount",
      "rel": "amend-brought-forward-loss",
      "method": "POST"
    }
  ]
}

=== hmrc/individual-losses-api/resources/public/api/conf/1.0/examples/broughtForwardLosses/retrieveBFLoss/retrieve_seClass4_response.json
{
  "typeOfLoss":"self-employment-class4",
  "selfEmploymentId": "XGIS00000001319",
  "lossAmount": 12345.67,
  "taxYear": "2018-19",
  "lastModified": "2018-07-13T12:13:48.763Z",
  "links":[
    {
      "href":"/individuals/TC663795B/income-tax/losses-brought-forward/1234568790ABCDE",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/TC663795B/income-tax/losses-brought-forward/1234568790ABCDE",
      "rel":"delete-brought-forward-loss",
      "method":"DELETE"
    },
    {
      "href":"/individuals/TC663795B/income-tax/losses-brought-forward/1234568790ABCDE/change-loss-amount",
      "rel":"amend-brought-forward-loss",
      "method":"POST"
    }
  ]
}
