=== hmrc/individual-losses-api/resources/public/api/conf/1.0/schemas/lossClaims/amendClaim/amend_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Amend a Loss Claim Response",
  "description": "Amend a Loss Claim Response",
  "type": "object",
  "properties": {
    "typeOfLoss": {
      "type": "string",
      "description": "The type of business the loss applies to.",
      "oneOf": [{"enum": ["self-employment"]}, {"enum": ["uk-property-non-fhl"]}]
    },
    "selfEmploymentId": {
      "type": "string",
      "pattern": "^X[A-Z0-9]{1}IS[0-9]{11}$",
      "description": "An identifier for the self-employment business, unique to the customer."
    },
    "typeOfClaim": {
      "type": "string",
      "description": "The type of claim to be applied. A self employment loss claim can only be of type carry-forward or carry-sideways.",
      "oneOf": [{"enum": ["carry-forward"]}, {"enum": ["carry-sideways"]}, {"enum": ["carry-sideways-fhl"]}, {"enum": ["carry-forward-to-carry-sideways"]}]
    },
    "taxYear": {
      "type": "string",
      "description": "The tax year the data applies to, for example, 2019-20. The tax year must not span more than one year for example, 2017-19 is not valid. The minimum tax year is 2019-20.",
      "pattern": "^2[0-9]{3}-[0-9]{2}$"
    },
    "lastModified": {
      "type": "string",
      "description": "The timestamp when the entry was created or last modified.",
      "pattern": "^2[0-9]{3}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{0,3}|)Z$"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint",
            "type": "string",
            "example": "/individuals/losses/{nino}/loss-claims/{claimId}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource",
            "type": "string",
            "enum": [
              "self"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint",
            "type": "string",
            "enum": [
              "GET"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ]
      }
    }
  },
  "required": ["typeOfLoss", "typeOfClaim", "taxYear", "lastModified"]
}

=== hmrc/individual-losses-api/resources/public/api/conf/3.0/examples/lossClaims/amendClaim/retrieve_non_fhl_response.json
{
    "typeOfLoss":"uk-property-non-fhl",
    "typeOfClaim": "carry-sideways",
    "taxYear": "2019-20",
    "lastModified" : "2020-07-11T12:15:34.734Z",
    "links": [
        {
            "href": "/individuals/losses/TC663795B/loss-claims/1234568790ABCDE",
            "rel": "self",
            "method": "GET"
        }
    ]
}
