=== hmrc/individual-losses-api/resources/public/api/conf/3.0/schemas/broughtForwardLosses/retrieveBFLoss/retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve a Brought Forward Loss",
  "description": "Retrieve a Brought Forward Loss Response",
  "type": "object",
  "properties": {
    "businessId": {
      "type": "string",
      "description": "An identifier for the business, unique to the customer.",
      "example": "XAIS12345678910",
      "pattern": "^X[A-Z0-9]{1}IS[0-9]{11}$"
    },
    "typeOfLoss": {
      "type": "string",
      "enum": [
        "self-employment",
        "self-employment-class4",
        "uk-property-fhl",
        "uk-property-non-fhl",
        "foreign-property-fhl-eea",
        "foreign-property"
      ],
      "description": "The type of business the loss applies to."
    },
    "lossAmount": {
      "type": "number",
      "description": "Brought Forward Loss amount related to the type of loss specified. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
      "example": "5000.99"
    },
    "taxYearBroughtForwardFrom": {
      "type": "string",
      "description": "The tax year to which the loss applies. The start year and end year must not span two tax years. No gaps are allowed, for example, 2020-22 is not valid. The minimum tax year is 2018-19. The tax year must have ended.",
      "example": "2022-23"
    },
    "lastModified": {
      "type": "string",
      "description": "The timestamp when the entry was created or last modified",
      "format": "date-time",
      "pattern": "^2[0-9]{3}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{0,3}|)Z$",
      "example": "2020-07-13T12:13:48.763Z"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/losses/{nino}/brought-forward-losses/{lossId}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self",
              "amend-brought-forward-loss",
              "delete-brought-forward-loss"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET",
              "POST",
              "DELETE"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "businessId",
    "typeOfLoss",
    "lossAmount",
    "taxYearBroughtForwardFrom",
    "lastModified"
  ],
  "additionalProperties": false
}

=== hmrc/individual-losses-api/resources/public/api/conf/3.0/examples/broughtForwardLosses/retrieveBFLoss/retrieve_se_response.json
{
  "businessId": "XBIS12345678911",
  "typeOfLoss": "self-employment",
  "lossAmount": 300.11,
  "taxYearBroughtForwardFrom": "2021-22",
  "lastModified": "2022-11-05T11:56:27Z",
  "links": [
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/AAZZ1234567890a",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/AAZZ1234567890a/change-loss-amount",
      "rel": "amend-brought-forward-loss",
      "method": "POST"
    },
    {
      "href": "/individuals/losses/TC663795B/brought-forward-losses/AAZZ1234567890a",
      "rel": "delete-brought-forward-loss",
      "method": "DELETE"
    }
  ]
}

=== hmrc/individual-losses-api/resources/public/api/conf/3.0/examples/broughtForwardLosses/retrieveBFLoss/retrieve_foreign_property_response.json
{
  "businessId": "XFIS12345678913",
  "typeOfLoss": "foreign-property",
  "lossAmount": 553.32,
  "taxYearBroughtForwardFrom": "2019-20",
  "lastModified": "2021-12-02T11:55:55Z",
  "links":[
    {
      "href":"/individuals/losses/{nino}/brought-forward-losses/{lossId}",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/losses/{nino}/brought-forward-losses/{lossId}",
      "rel":"delete-brought-forward-loss",
      "method":"DELETE"
    },
    {
      "href":"/individuals/losses/{nino}/brought-forward-losses/{lossId}/change-loss-amount",
      "rel":"amend-brought-forward-loss",
      "method":"POST"
    }
  ]
}
